platform :ios, '7.0'
xcodeproj 'IdrisTouch/IdrisTouch.xcodeproj'
# inhibit_all_warnings!

pod 'DCIntrospect'
pod 'ReactiveCocoa', '~>2.2.0'
pod 'libextobjc', '~>0.4'
pod 'Masonry'
pod 'GCNetworkReachability'
pod 'Classy'
pod 'ClassyLiveLayout', :head
pod 'EKKeyboardAvoiding'

# Only for debug. Remove before shipping
pod 'Reveal-iOS-SDK'
pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'



